import java.io.*;
import java.net.Socket;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ServerThread implements Runnable {

    private static final String DOCUMENT_ROOT = "server/src/main/resources/web";
    private static final String ERROR_DOCUMENT = "server/src/main/resources";
    
    private Socket socket;

    public ServerThread(Socket socket) {
        this.socket = socket;
    }

    @Override
    public void run() {
        try {

            String line;
            String path = null;
            String ext = null;
            InputStream input = socket.getInputStream();
            while ((line = Util.readLine(input)) != null) {
                if (line.isEmpty()) break;
                if (line.startsWith("GET")) {
                    path = line.split(" ")[1];
                    String[] tmp = path.split("\\.");
                    ext = tmp[tmp.length - 1];
                }
            }

            OutputStream output = socket.getOutputStream();
            try (FileInputStream inputStream = new FileInputStream(DOCUMENT_ROOT + path)) {
                SendResponse.sendOkResponse(output, inputStream, ext);
            } catch (FileNotFoundException ex) {
                SendResponse.sendNotFoundResponse(output, ERROR_DOCUMENT);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try{
                socket.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

}
