import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Client01 {
    public static void main(String[] args) {
        try (Socket socket = new Socket("localhost", 8001);
             FileInputStream fis = new FileInputStream("client/src/main/resources/client_send.txt");
             FileOutputStream fos = new FileOutputStream("client/src/main/resources/client_recv.txt")) {

            int ch;
            // client_send.txtの内容をサーバに送信
            OutputStream output = socket.getOutputStream();
            while ((ch = fis.read()) != -1) {
                output.write(ch);
            }
            // 終了を示すため、ゼロを送信
            output.write(0);
            // サーバからの返信をclient_recv.txtに出力
            InputStream input = socket.getInputStream();
            while ((ch = input.read()) != -1) {
                fos.write(ch);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
